[FIX] base_import_pdf_by_template: Proper argument name
The signature of the method `_message_post_after_hook` is
`self, message, msg_vals`. Using other variable names has the risk of
other overrides calling `super` using keyword arguments to fail, as it
happens with a combination of installed modules:

```
    self._message_post_after_hook(new_message, values)
  File "/opt/odoo/auto/addons/mail/models/mail_channel.py", line 617, in _message_post_after_hook
    return super()._message_post_after_hook(message=message, msg_vals=msg_vals)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 658, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause

TypeError: _message_post_after_hook() got an unexpected keyword argument 'message'
```

TT58526